# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: txsigner.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'txsigner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etxsigner.proto\x12\x08txsigner\"4\n\x0b\x41\x63\x63\x65ssTuple\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\x14\n\x0cstorage_keys\x18\x02 \x03(\x0c\"\xc4\x01\n\x04TxIn\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\x04\x12\r\n\x05nonce\x18\x02 \x01(\x04\x12 \n\x18max_priority_fee_per_gas\x18\x03 \x01(\x0c\x12\x17\n\x0fmax_fee_per_gas\x18\x04 \x01(\x0c\x12\x0b\n\x03gas\x18\x05 \x01(\x04\x12\n\n\x02to\x18\x06 \x01(\x0c\x12\r\n\x05value\x18\x07 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x08 \x01(\x0c\x12*\n\x0b\x61\x63\x63\x65ss_list\x18\t \x03(\x0b\x32\x15.txsigner.AccessTuple\"6\n\x0bSignRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x1b\n\x03txs\x18\x02 \x03(\x0b\x32\x0e.txsigner.TxIn\"7\n\x0cSignResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0b\n\x03raw\x18\x02 \x03(\x0c\x12\x0e\n\x06\x65rrors\x18\x03 \x03(\tB9Z7github.com/NethermindEth/eth-perf-research/tx-signer/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'txsigner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/NethermindEth/eth-perf-research/tx-signer/pb'
  _globals['_ACCESSTUPLE']._serialized_start=28
  _globals['_ACCESSTUPLE']._serialized_end=80
  _globals['_TXIN']._serialized_start=83
  _globals['_TXIN']._serialized_end=279
  _globals['_SIGNREQUEST']._serialized_start=281
  _globals['_SIGNREQUEST']._serialized_end=335
  _globals['_SIGNRESPONSE']._serialized_start=337
  _globals['_SIGNRESPONSE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
