tags: python, rpc
params:
  - RPC_URL: "http://172.233.124.18:8545"
steps:
  - name: check last 5 blocks not empty
    command: uv run /root/.config/dagu/scripts/check_last_5_blocks_not_empty.py --url $RPC_URL
    output: CHECK_RESULT
  - name: use output
    command: echo "${CHECK_RESULT}"
    preconditions:
      - condition: "${CHECK_RESULT}"
        expected: "true"
    depends:
      - check last 5 blocks not empty
