services:
  dagu:
    image: "ghcr.io/dagu-org/dagu:latest"
    container_name: dagu
    hostname: dagu
    ports:
      - "8092:8080"
    environment:
      - DAGU_PORT=8080 # optional. default is 8080
    volumes:
      - ./config/dags:/root/.config/dagu/dags
      - ./config/scripts:/root/.config/dagu/scripts
      - ./config/logs:/root/.local # to keep history and logs
      - ./init.sh:/init.sh # Mount the initialization scrip
      - /var/run/docker.sock:/var/run/docker.sock # optional. required for docker in docker
    command: sh -c "chmod +x /init.sh && /init.sh && dagu start-all"
    user: "0:0"
    entrypoint: [] # Override any default entrypoint
