# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: builder.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'builder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from orchestrator._proto import txsigner_pb2 as txsigner__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbuilder.proto\x12\x07\x62uilder\x1a\x0etxsigner.proto\"\x90\x02\n\x0f\x46\x61\x63\x61\x64\x65\x43txParams\x12\x14\n\x0c\x62\x61se_address\x18\x01 \x01(\x0c\x12\x10\n\x08revision\x18\x02 \x01(\x04\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\x04\x12\x17\n\x0f\x62lock_gas_limit\x18\x04 \x01(\x04\x12\x13\n\x0bsalt_cursor\x18\x05 \x01(\x04\x12\x46\n\x10verb_gas_factors\x18\x06 \x03(\x0b\x32,.builder.FacadeCtxParams.VerbGasFactorsEntry\x12\x16\n\x0e\x61\x64\x64ress_stride\x18\x07 \x01(\x04\x1a\x35\n\x13VerbGasFactorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"v\n\x11\x42uildBatchRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04verb\x18\x02 \x01(\t\x12\x11\n\tstart_idx\x18\x03 \x01(\x04\x12\r\n\x05\x63ount\x18\x04 \x01(\r\x12%\n\x03\x63tx\x18\x05 \x01(\x0b\x32\x18.builder.FacadeCtxParams\"\x19\n\tBuildDiag\x12\x0c\n\x04json\x18\x01 \x01(\t\"\x8e\x01\n\x12\x42uildBatchResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12!\n\tsignables\x18\x02 \x03(\x0b\x32\x0e.txsigner.TxIn\x12!\n\x05\x64iags\x18\x03 \x03(\x0b\x32\x12.builder.BuildDiag\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x17\n\x0fnew_salt_cursor\x18\x05 \x01(\x04\x42PZNgithub.com/NethermindEth/eth-perf-research/orchestrator/internal/orchpb;orchpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'builder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZNgithub.com/NethermindEth/eth-perf-research/orchestrator/internal/orchpb;orchpb'
  _globals['_FACADECTXPARAMS_VERBGASFACTORSENTRY']._loaded_options = None
  _globals['_FACADECTXPARAMS_VERBGASFACTORSENTRY']._serialized_options = b'8\001'
  _globals['_FACADECTXPARAMS']._serialized_start=43
  _globals['_FACADECTXPARAMS']._serialized_end=315
  _globals['_FACADECTXPARAMS_VERBGASFACTORSENTRY']._serialized_start=262
  _globals['_FACADECTXPARAMS_VERBGASFACTORSENTRY']._serialized_end=315
  _globals['_BUILDBATCHREQUEST']._serialized_start=317
  _globals['_BUILDBATCHREQUEST']._serialized_end=435
  _globals['_BUILDDIAG']._serialized_start=437
  _globals['_BUILDDIAG']._serialized_end=462
  _globals['_BUILDBATCHRESPONSE']._serialized_start=465
  _globals['_BUILDBATCHRESPONSE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
